spring:
  application:
    name: whereclass-backend
  data:
    mongodb:
      host: localhost
      port: 27017
      database: whereclass

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.whereclass: DEBUG
    org.springframework.data.mongodb: DEBUG